return {
  -- {
  --   "leoluz/nvim-dap-go",
  --   enabled = false,
  -- },
  -- {
  --   "mfussenegger/nvim-dap",
  --   enabled = false,
  -- },
  -- {
  --   "fredrikaverpil/neotest-golang",
  --   enabled = false,
  -- },
  -- {
  --   "nvim-neotest/neotest",
  --   enabled = false,
  -- },
  -- {
  --   "nvimtools/none-ls.nvim",
  --   enabled = false,
  -- },
  -- { "mfussenegger/nvim-lint", enabled = false },
}
