#!/bin/bash

# Panels
# bspc config top_padding               35
#bspc config bottom_padding              25

bspc config border_width                2
bspc config window_gap                  10
bspc config split_ratio                 0.52
bspc config borderless_monocle          false
bspc config gapless_monocle             false

bspc config active_border_color         "#545350"
bspc config focused_border_color        "#F4BE36"
#bspc config active_border_color         "#545350"
#bspc config focused_border_color        "#7E7F89"

# Multihead behavior
bspc config remove_disabled_monitors    true
bspc config remove_unplugged_monitors   true
#bspc config persistent_monitors         true
#bspc config pointer_follows_monitor     true

# Focusing behavior
#bspc config pointer_follows_focus       true
#bspc config pointer_follows_monitor     true
bspc config focus_follows_pointer       true
bspc config history_aware_focus         true
bspc config ignore_ewmh_focus           true

# Misc
bspc config split_ratio                 0.50
#bspc config auto_alternate              true
#bspc config auto_cancel                 true
#bspc config adaptative_raise            true

# Set up displays
# bspc monitor --reset-desktops 1
# bspc monitor --add-desktops 2
# bspc monitor --remove-desktops 2

# bspc monitor -d 01 02 03 04 05 06 07 08 09 10

# Setup monitors
if [ "$(bspc query -M | wc -l)" -eq "3" ]; then
  bspc monitor $(bspc query -M | sed -n 1p) -d 00 03 06 09
  bspc monitor $(bspc query -M | sed -n 2p) -d 01 04 07
  bspc monitor $(bspc query -M | sed -n 3p) -d 02 05 08
elif [ "$(bspc query -M | wc -l)" -eq "2" ]; then
  bspc monitor $(bspc query -M | sed -n 1p) -d 00 02 04 06 08
  bspc monitor $(bspc query -M | sed -n 2p) -d 01 03 05 07 09
else
  bspc monitor -d 00 01 02 03 04 05 06 07 08 09
fi

# Setup Monitors
# i=1
# for monitor in $(bspc query -M); do
#     bspc monitor $monitor \
#         -n "$i" \
#         -d {01,02,03,04,05,06,07,08,09}
#     let i++
# done
# unset i

bspc wm --adopt-orphans

# Rules
bspc rule -a Nitrogen state=floating
bspc rule -a chrome_app_list state=floating
bspc rule -a google-chrome:crx_gaedmjdfmmahhbjefcbgaolhhanlaolb state=floating center=on # Authy
bspc rule -a Telegram state=pseudo_tiled
bspc rule -a Viewnior state=floating center=on
bspc rule -a Xarchiver state=floating center=on
